site_name: My Docs
theme:
  name: material
site_url: https://sharshi.github.io/t
plugins:
  - blogging:
      dirs:
        - posts
  - mkdocs-breadcrumbs-plugin:
      delimiter: " / "  # separator between sections
      log_level: "WARNING"  # "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"
      exclude_paths:
        - "docs/mkdocs/**"
        - "docs/mkdocs"   # avoid generating index.md
      additional_index_folders:
        - temp_dir
      generate_home_index: false
locale: en
time_format: '%Y-%m-%d %H:%M:%S'
meta_time_format: '%Y-%m-%d %H:%M:%S'
