site_name: info
site_url: https://sharshi.github.io/t

nav:
  - index.md
  - Blog:
    - posts/index.md

plugins:
  - search
  - blog:
    blog_dir: posts


theme:
  name: material
  features:
    - navigation.indexes