site_name: info
site_url: https://sharshi.github.io/t

nav:
  - index.md
  - Posts:
    - posts/index.md
  - Projects:
    - projects/index.md

plugins:
  - search
  - blog:
      blog_dir: posts

theme:
  name: material
  features:
    - navigation.indexes

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
