site_name: My Docs
theme:
  name: material
site_url: https://sharshi.github.io/t
plugins:
  - blogging:
      dirs:
        - posts
locale: en
time_format: '%Y-%m-%d %H:%M:%S'
meta_time_format: '%Y-%m-%d %H:%M:%S'
