site_name: info
site_url: https://sharshi.github.io/t

nav:
- Home: index.md
- Posts: posts/index.md


plugins:
  - blogging:
      dirs:
        - posts
  - mkdocs-breadcrumbs-plugin:
      delimiter: " 𓉱 "
      exclude_paths:
        - "docs/mkdocs/**"
        - "docs/mkdocs"
      additional_index_folders:
        - temp_dir
      generate_home_index: false

locale: en
time_format: '%Y-%m-%d %H:%M:%S'
meta_time_format: '%Y-%m-%d %H:%M:%S'

theme:
  name: material
