site_name: Shersheial Borisute
site_url: https://www.sharshi.com

nav:
  - index.md
  - Posts:
    - posts/index.md
  - Projects:
    - projects/index.md
    - Siddur: projects/siddur.md
    - 'Web Hunt': projects/webhunt.md
    - 'Tidy Albatross': projects/tidy-albatross.md

nav_title: Menu
  
plugins:
  - search
  - blog:
      blog_dir: posts
      blog_toc: true
      archive_toc: true

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.expand
  custom_dir: overrides
  extra:
    comments: true
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
